language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      name: Python Xenial
      addons:
        apt:
          packages:
            - cmake
            - libboost-all-dev
            - libsdl2-dev
            - libfreetype6-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libpng-dev
            - libjpeg-dev
            - libbz2-dev
            - libfluidsynth-dev
            - libgme-dev
            - libopenal-dev
            - zlib1g-dev
            - timidity
            - tar
            - nasm
            - wget
            - python3-dev
            - python3-numpy
            - python3-pip
      script:
        - |
          python3 --version
          python3 -m pip install --upgrade pip
          python3 -m pip -v install .
    - os: linux
      dist: bionic
      name: Python Bionic
      addons:
        apt:
          packages:
            - cmake
            - libboost-all-dev
            - libsdl2-dev
            - libfreetype6-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libpng-dev
            - libjpeg-dev
            - libbz2-dev
            - libfluidsynth-dev
            - libgme-dev
            - libopenal-dev
            - zlib1g-dev
            - timidity
            - tar
            - nasm
            - wget
            - python3-dev
            - python3-numpy
            - python3-pip
      script:
        - |
          python3 --version
          python3 -m pip install --upgrade pip
          python3 -m pip -v install .
    - os: osx
      name: Python MacOS
      addons:
        homebrew:
          packages:
            - cmake
            - boost
            - sdl2
            - wget
      script:
        - |
          python --version
          python -m pip -v install .
